# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_auto_20161011_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='song',
            name='song_ext',
            field=models.CharField(default='', max_length=10),
        ),
    ]
