# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_auto_20161011_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_ext',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
