# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_auto_20161013_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.CharField(max_length=10),
        ),
    ]
