# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0009_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user_songs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
